### ISSUE TITLE
cuda out of memory in V100 GPU (32GB)

### ISSUE THREAD

**Issue by Fangkang515** [daspartho/MagicMix#1]
Thank you for your work. 
I would like to ask how much GPU memory is required to run this code.
I found that there will be errors on the 32G V100 GPU.

Looking forward to your reply.

**Comment by daspartho** [comment]
hmm that shouldn't happen- i had run this on google colab with way weaker GPU so something must be wrong! could you give me some more info on your run?

**Comment by daspartho** [comment]
the [hugginface space](https://huggingface.co/spaces/daspartho/MagicMix) for the project is running on a T4 small with 16GB VRAM

**Comment by Fangkang515** [comment]
Thanks for your reply. 

I have known the cause of the out-of-memory problem. It's the image resolution. 

I used your provided codes, and changed the image resolution,

`img = Image.open('phone.jpg').resize((512,512))`

now it works well.


Thank you again.

**Comment by daspartho** [comment]
awesome!
